AllCops:
  Exclude:
    - 'db/schema.rb'
    - log/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
  Max: 20
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
AsciiComments:
  Enabled: false
