version: "3.7"
services:
  app:
    container_name: vue-rails-sample
    tty: true
    stdin_open: true
    image: dofa-app
    volumes: 
      - "./.:/app/vue-rails-sample:cached"
      - vendor:/app/vue-rails-sample/vendor
      - node_modules:/app/vue-rails-sample/node_modules
      # 不要なディレクトリを上書き
      - /opt/kasooku/tmp
      - /opt/kasooku/log
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3001 -b 0.0.0.0"
    ports: 
      - "3001:3001"
    build:
      context: .
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "13306:3306"
    volumes: 
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
  vendor:
    driver: local
  node_modules:
    driver: local
